import {Constants} from '@stripe/stripe-react-native';

export const FETCH_CATEGORIES = 'FETCH_CATEGORIES';
export const FETCH_JOBS = 'FETCH_JOBS';
export const TOGGLE_CATEGORY = 'TOGGLE_CATEGORY';
export const FETCH_CATEGORIES_REQUEST = 'FETCH_CATEGORIES_REQUEST';
export const FETCH_CATEGORIES_SUCCESS = 'FETCH_CATEGORIES_SUCCESS';
export const FETCH_CATEGORIES_FAILURE = 'FETCH_CATEGORIES_FAILURE';
export const FETCH_JOBS_REQUEST = 'FETCH_JOBS_REQUEST';
export const FETCH_JOBS_SUCCESS = 'FETCH_JOBS_SUCCESS';
export const FETCH_JOBS_FAILURE = 'FETCH_JOBS_FAILURE';
export const TOGGLE_THEME = 'TOGGLE_THEME';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';

export const POST_JOBS_REQUEST = 'POST_JOBS_REQUEST';
export const POST_JOBS_SUCCESS = 'POST_JOBS_SUCCESS';
export const POST_JOBS_FAILURE = 'POST_JOBS_FAILURE';

export const PAYMENT_REQUEST = 'PAYMENT_REQUEST';
export const PAYMENT_SUCCESS = 'PAYMENT_SUCCESS';
export const PAYMENT_FAILURE = 'PAYMENT_FAILURE';

export const FETCH_SPOTLIGHT_REQUEST = FETCH_SPOTLIGHT_REQUEST;
export const FETCH_SPOTLIGHT_SUCCESS = FETCH_SPOTLIGHT_SUCCESS;
export const FETCH_SPOTLIGHT_FAILURE = FETCH_SPOTLIGHT_FAILURE;

export const UPDATE_PROVIDER_STATUS = 'UPDATE_PROVIDER_STATUS';
export const FETCH_SERVICEPROVIDER_DETAILS = 'FETCH_SERVICEPROVIDER_DETAILS';

export const ADD_TO_FAVOURITE = 'ADD_TO_FAVOURITE';
export const REMOVE_FROM_FAVOURITE = 'REMOVE_FROM_FAVOURITE';

export const FETCH_APPLIEDJOBS_SUCCESS = 'FETCH_APPLIEDJOBS_SUCCESS';
export const FETCH_APPLIEDJOBS_FAILURE = 'FETCH_APPLIEDJOBS_FAILURE';

export const FETCH_JOBAPPLIED_PROFILES_SUCCESS = 'FETCH_JOBAPPLIED_PROFILES';
export const FETCH_JOBAPPLIED_PROFILES_FAILURE = 'FETCH_JOBAPPLIED_PROFILES_FAILURE';

export const STORE_CHECKPROFILE_JOB_DETAILS = 'STORE_CHECKPROFILE_JOB_DETAILS';
export const STORE_APPLICANTSPROFILE_DETAILS = 'STORE_APPLICANTSPROFILE_DETAILS';

export const FETCH_SELECTED_PROFILES_SUCCESS = 'FETCH_SELECTED_PROFILES';

export const FETCH_SELECTED_PROFILES_FAILURE = 'FETCH_SELECTED_PROFILES_FAILURE';
export const FETCH_SELECTED_JOBS_SUCCESS = 'FETCH_SELECTED_JOBS_SUCCESS';

export const FETCH_COMPLETED_JOBS_SUCCESS = 'FETCH_COMPLETED_JOBS_SUCCESS';
export const CURRENT_LOCATION = 'CURRENT_LOCATION';
export const PERMISSION = 'PERMISSION';
export const LATLANG = 'LATLANG';
export const FETCHSUBCATEGORYNAME = 'FETCHSUBCATEGORYNAME';

export const GET_SELECTED_JOB_DETAILS = 'GET_SELECTED_JOB_DETAILS';

export const SET_EDIT_JOB_STATUS = 'SET_EDIT_JOB_STATUS';
